config/routes.rb
BBPHealth::Application.routes.draw do

  scope "(:locale)", :locale => /en|fr/,  :defaults => {:locale => ""} do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get '/users/auth/:provider/setup'   => 'users/omniauth_callbacks#setup'
      get '/users/auth/facebook/callback' => 'users/omniauth_callbacks#facebook'
    end

    resources :medications do
      collection do
        get :search 
        get :list
        get :elastic_search
      end
      member do
        get :map
      end
      resources :secondary_effects
    end
    
    root :to => "medications#index"
    match "secondary_effects" =>"secondary_effects#index" 
  end

  get '/map/:id/clusterize' => 'map#clusterize'
  get '/map/:id/select'     => 'map#select'
end

app/models/concern/secondary_effects.rb
module Concern
  module SecondaryEffects
    extend ActiveSupport::Concern

    included do
      include Mongoid::TaggableWithContext
      include Mongoid::TaggableWithContext::AggregationStrategy::RealTime

      taggable :secondary_effects, :separator => ','
    end

    module ClassMethods
      def analyze_secondary_effect_facets(result, term)
        result.facets['secondary_effects']["terms"].map! do |facet|
          facet['selected']     = term.include?(facet['term'])
          facet['remove_facet'] = (term - [facet["term"]])  * ","
          facet['add_facet']    = (term + [facet["term"]]) * ","
          facet
        end
      end
    end
  end
end

app/controllers/secondary_effects_controller.rb
class SecondaryEffectsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :update, :new, :edit]
  before_filter :find_medication, :only => [:create, :new]
  def index
    @se = Medication.secondary_effects
    respond_to do |format|
      format.html {}
      format.json { render json: @se.map {|se|
       if (params[:term].present? && se.downcase.include?(params[:term].downcase))  then
         {'id'=> se.downcase, 'label'=> se, 'value'=> se}
         end
      }.compact.sort_by { |my_item| my_item[:id] }}
    end
  end

  def create
    if params[:known_effects]
      fx = (params[:prescription][:secondary_effects].split(',') + params[:known_effects]).flatten.uniq.join(',')
      params[:prescription][:secondary_effects] = fx
    end
    @prescription = @medication.prescriptions.build(params[:prescription].merge(user_agent: request.user_agent, user: current_user))

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @medication, notice: t("medications.flash.success") }
        format.json { render json: @prescription, status: :created, location: @prescription }
      else
        format.html { render action: "new" }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @prescription = @medication.prescriptions.build
  end

protected

  def find_medication
     @medication = Medication.find_by_slug(params[:medication_id])
     @prescriptions = Prescription.elastic_search @medication, params
     @facets = @prescriptions.facets['secondary_effects']["terms"]
  end

end

app/views/secondary_effects/index.html.erb
<h1>Not implemented</h1>

app/views/secondary_effects/new.html.erb
<h2>
  <%= @medication.name %>
  <% unless @medication.generic_name.blank? %>
    <small> - <%= @medication.generic_name %></small>
  <% end %>
</h2>
<%= simple_form_for(@prescription, :url => medication_secondary_effects_path(@medication), :html => {:class => 'form-horizontal' }) do |form| %>
  <div class="control-group text optional">
    <label class="text optional control-label" for="prescription_secondary_effects">
      <%= t('simple_form.labels.prescription.kwon_secondary_effects') %>
    </label>
    <div class="controls">
        <% @facets.each_with_index do |term, index| %>
        <div class="known_facet">
          <%= check_box_tag "term_#{index}", term["term"], false, :name => "known_effects[]" %>
          <label for="term_<%= index %>">
            <%= term["term"] %> (<%= term["count"] %>)
          <label>
        </div>
        <% end %>
    </div>
  </div>

  <%= form.input :secondary_effects, :as => :text, :input_html => {:class => :span, :id => :secondary_effects_field} %>

  <%= form.input :experience, :as => :text %>
  <%= form.input :lat, :as => :hidden %>
  <%= form.input :lng, :as => :hidden %>

  <div class="form-actions">
    <%= form.button :submit, :class => 'btn btn-primary', :id => :submit_with_secondary_effect %>
    <%= link_to t(:cancel), :back , :class=>"btn" %>
  </div>
<% end %>