config/routes.rb
BBPHealth::Application.routes.draw do

  scope "(:locale)", :locale => /en|fr/,  :defaults => {:locale => ""} do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get '/users/auth/:provider/setup'   => 'users/omniauth_callbacks#setup'
      get '/users/auth/facebook/callback' => 'users/omniauth_callbacks#facebook'
    end

    resources :medications do
      collection do
        get :search 
        get :list
        get :elastic_search
      end
      member do
        get :map
      end
      resources :secondary_effects
    end
    
    root :to => "medications#index"
    match "secondary_effects" =>"secondary_effects#index" 
  end

  get '/map/:id/clusterize' => 'map#clusterize'
  get '/map/:id/select'     => 'map#select'
end

app/models/medication.rb
class Medication

  include Mongoid::Document
  include Mongoid::Slug
  include Mongoid::Timestamps

  include Concern::SecondaryEffects
  include Concern::Searchable

  field :name, :type => String
  field :generic_name, :type => String

  mapping do
    indexes :name
    indexes :generic_name
    # Define correct analyzer for secondary_effects array
    indexes :secondary_effects_array, :analyzer => 'keyword', :type => 'string'
  end

  validates :name, :presence => true, :on => :create
  validates :name, :uniqueness => true

  attr_accessor :lat, :lng, :user_agent, :user, :experience
  attr_accessible :user_agent, :secondary_effects, :name, :generic_name, :lat, :lng, :experience

  slug :name, :permanent => true, :index => true

  has_many :prescriptions, dependent: :destroy

  after_create :create_prescription

  class << self
    def elastic_search(params)
      query = params[:q].present? ? "*#{params[:q]}*" : "*"
      t = params[:terms].present? ? params[:terms].split(',')  : []

      result = tire.search(page: params[:page], per_page: params[:per_page] || 10, load: true) do
        query { string query, default_operator: "AND" }
        filter :terms, :secondary_effects_array => t if t != []
        facet ("secondary_effects") { terms :secondary_effects_array, :global => false}
      end
      analyze_secondary_effect_facets result, t
      result
    end
  end

  def update_tags!
    self.secondary_effects_array = prescriptions.map(&:secondary_effects_array).flatten.uniq
    save!
  end

  def has_geo_data?
    prescriptions.where( "location.latitude" => {"$ne" => nil}).count > 0
  end

private
  def create_prescription
    lat = self.lat.nil? ? nil : self.lat.to_f
    lng = self.lng.nil? ? nil : self.lng.to_f
    prescriptions.create!(lat: lat, lng: lng, user_agent: user_agent, user: user, secondary_effects: secondary_effects, experience: experience)
  end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :new]
  before_filter :authenticate_admin, :only => [:list, :edit, :update, :destroy]
  before_filter :get_medication_and_facets, :only => [:show, :map]
  # GET /medications
  # GET /medications.json
  def index
    @home_page = true
    @last_added_medications = Medication.order_by([[:updated_at, :desc]]).limit(10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medications }
    end
  end

  # GET /medications/search
  def elastic_search
    @search = params[:q]
    @medications = Medication.elastic_search params

    @facets      =  @medications.facets['secondary_effects']["terms"]
    respond_to do |format|
       format.html
       format.json { render json: @medications }
     end
  end

  def search
    @medications = Medication.where(:name => params[:q])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medications }
    end
  end


  # GET /medications/1
  # GET /medications/1.json
  def show
    @prescriptions     = @medication.prescriptions.order_by([:created_at, :desc])
    @secondary_effects = @prescriptions.with_secondary_effects.page(params[:page]).per(10)
    @experiences       = @prescriptions.with_experience
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medication }
    end
  end

  def map
  end

  # GET /medications/new
  # GET /medications/new.json
  def new
    @medication = Medication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medication }
    end
  end

  # POST /medications
  # POST /medications.json
  def create
    @medication = Medication.new(params[:medication].merge(user_agent: request.user_agent))
    @medication.user = current_user

    respond_to do |format|
      if @medication.save
        format.html { redirect_to @medication, notice: t("medications.flash.success") }
        format.json { render json: @medication, status: :created, location: @medication }
      else
        format.html { render action: "new" }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  ## ADMIN PART ##

  # GET /medications/1/edit
  def edit
    @medication = Medication.find_by_slug(params[:id])
  end

  # PUT /medications/1
  # PUT /medications/1.json
  def update
    @medication = Medication.find_by_slug(params[:id])

    respond_to do |format|
      if @medication.update_attributes(params[:medication])
        format.html { redirect_to @medication, notice: 'Medication was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medications/1
  # DELETE /medications/1.json
  def destroy
    @medication = Medication.find_by_slug(params[:id])
    @medication.destroy

    respond_to do |format|
      format.html { redirect_to medications_url }
      format.json { head :ok }
    end
  end

  def list
    @medications = Medication.page(params[:page]).per(10)
  end


private
  def get_medication_and_facets
    @medication = Medication.find_by_slug(params[:id])
    @prescriptions = Prescription.elastic_search @medication, params
    @facets = @prescriptions.facets['secondary_effects']["terms"]
  end

end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_actions.html.erb
<div class="row actions">
  <div class='pull-left'>

    <%= link_to medication_path(medication.slug), class: "btn btn-small btn-info"  do %>
      <i class="icon-info-sign icon-white"></i> <span class="hidden-phone"><%= t(:show) %></span>
    <% end if with_show%>
    <%= link_to new_medication_secondary_effect_path(medication.slug), class: "btn btn-small btn-primary"  do %>
      <i class="icon-plus icon-white"></i> <span class="hidden-phone"><%= t(:'medications.add_effects') %></span>
    <% end %>

    <% if medication.has_geo_data? %>
      <%= link_to map_medication_path(medication.slug), class: "btn btn-small btn-success"  do %>
        <i class="icon-map-marker icon-white"></i> <span class="hidden-phone"><%= t(:map) %></span>
      <% end %>
    <% end %>
  </div>

  <% if admin? %>
    <div class='pull-right' style="padding-right:10px">
      <%= link_to edit_medication_path(medication.slug), class: "btn"  do %>
        <i class="icon-cog"></i> <span class="hidden-phone"><%= t(:edit) %></span>
      <% end %>
      <%= link_to medication_path(medication.slug), confirm: 'Are you sure?', method: :delete, class: "btn btn-danger"  do %>
        <i class="icon-trash icon-white"></i> <span class="hidden-phone"><%= t(:delete) %></span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/medications/_elastic_search_facets.html.erb
<h3><%= t('simple_form.labels.medication.secondary_effects') %></h3>
<ul>
  <% @facets.each do |term| %>   
    <li>
      <%= link_to term["term"],  :action => "elastic_search",  :q => params[:q],  :terms => term["add_facet"] %> (<%= term["count"] %>) 
      <strong>
        <%= link_to "X", :action => "elastic_search",  :q => params[:q], :terms => term["remove_facet"]  if term["selected"] %>
      </strong>
    </li>
  <% end %>               
</ul>

app/views/medications/_form.html.erb
<%= simple_form_for(@medication, :html => {:class => 'form-horizontal' }) do |form| %>
  <%= form.input :name, :input_html => {:class => :span} %>
  <%= form.input :generic_name, :input_html => {:class => :span} %>
  <%  if @medication.new_record? %>
    <%= form.input :secondary_effects, :as => :text, :input_html => {:class => :span, :id => :secondary_effects_field} %>
    <%= form.input :experience, :as => :text %>
    <%= form.input :lat, :as => :hidden %>
    <%= form.input :lng, :as => :hidden %>
  <% end %>
  <div class="form-actions">
    <%= form.button :submit, :class => 'btn btn-primary', :id => :submit_with_secondary_effect %>
    <%= link_to t(:cancel), :back , :class=>"btn" %>
  </div>
<% end %>

app/views/medications/_list.html.erb
<% @medications.each do |medication| %>
  <div class="container well medication_list">
    <div class="row">
      <h3>
        <%= medication.name %>
        <% unless medication.generic_name.blank? %>
          <small> - <%= medication.generic_name %></small>
        <% end %>
        <em>(<%= medication.prescriptions.count %>)</em>
      </h3>
    </div>
    <div class="row">
      <span class="hidden-phone"><%= t('simple_form.labels.medication.secondary_effects') %> : </span></span>
      <% medication.secondary_effects_array.each do |tag| %>
        <span class="label label-info"><%= tag %></span>
      <% end  %>
    </div>
    <%= render "actions", medication: medication, with_show: true %>
  </div>
<% end %>
<%= paginate @medications %>

app/views/medications/edit.html.erb
<h2><%= t('medications.edit_title') %></h2>

<%= render 'form' %>

app/views/medications/elastic_search.html.erb
<h2><%= t('search.title', :for => @search) %></h2>
<%= render 'list' %>      
<%= render 'elastic_search_facets' %>
<br />
<%= link_to t('medications.add_title'), new_medication_path, :class=>"link" %>

app/views/medications/index.html.erb
<h2><%= t('medications.title') %></h2>

<div id='search-box'>
  <%= form_tag elastic_search_medications_path, :method => 'get', :class => 'searchform', :id => 'search-form' do %>
    <%= text_field_tag :q, params[:q], :class => "input-medium search-query", :id => 'search-text', :placeholder => 'Ex: Ibuprofene, Lisopaïne, ...' %>
    <%= button_tag :id => "search-button", :type => :submit do %>
      <span><%= t('medications.search') %></span>
    <% end %>
<% end %>
</div>
<div class="centered">
  <%= link_to t('medications.add_title'), new_medication_path, :class=>"link" %>
<div>
<h2><%= t('medications.last_added') %></h2>
- <% @last_added_medications.each do |medication| %>
  <%= link_to medication.name, medication_path(medication) %> -
<% end %>

app/views/medications/list.html.erb
<h2>Medication listing</h2>

<%= render 'list', admin_mode: true %>      
<%= link_to t('medications.add_title'), new_medication_path, :class=>"link" %>

app/views/medications/map.html.erb
<h2><%= t(:'maps.title', name: "#{@medication.name}/#{@medication.generic_name}") %></h2>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4  form-search" id="filters">
      <div class="well">
        <div data-condition="medication_id=<%= @medication.id %>"></div>
        <div>
          <h3><%= t(:'simple_form.labels.medication.secondary_effects') %></h3>
          <% @facets.each do |term| %>
            <label class="checkbox">
              <input type="checkbox" value="<%= term["term"] %>" data-condition='secondary_effects:"<%= term["term"] %>"'>
              <%= term["term"] %> (<%= term["count"] %>)
            </label><br/>
          <% end %>
        </div>
        <h3><%= t(:'simple_form.labels.medication.timing') %></h3>
        <div data-condition="created_at:[? TO ?]" data-condition-type="range">
          <%= t(:from) %> <input id="from" type="text" class="datepicker from"/><br/>
          <%= t(:to) %> <input id="to" type="text" class="datepicker to"/><br/>
        </div>
      </div>
      <%= link_to new_medication_secondary_effect_path(@medication.slug), class: "btn btn-small btn-primary" do %>
        <i class="icon-plus icon-white"></i> <span><%= t(:'medications.add_effects') %></span>
      <% end %>
    </div>
    <div class="span8">
      <div id='map'><div>
    </div>
  </div>
</div>
<%= content_for :tail do %>
  <%= javascript_tag "Map.init('#{@medication.slug}')" %>
<% end %>

<%= content_for :head do %>
  <script src="http://maps.googleapis.com/maps/api/js?v=3&amp;sensor=false"></script>
<% end %>

app/views/medications/new.html.erb
<h2><%= t('medications.add_title') %></h2>

<%= render 'form' %>

<div id ="search_result"></div>  

app/views/medications/search.html.erb
<h1>Mongo Search results medications</h1>

<%= render 'list' %>               


<br />
                  
<%= link_to 'New Medication', new_medication_path, :class=>"btn" %>

app/views/medications/show.html.erb
<div class="medication_show">
  <h2>
    <%= @medication.name %>
    <% unless @medication.generic_name.blank? %>
      <small> - <%= @medication.generic_name %></small>
    <% end %>
  </h2>

  <p>
    <b><%= t('simple_form.labels.medication.nb_users') %>:</b>
    <%= @secondary_effects.count %>
  </p>
  <p>
    <b><%= t('simple_form.labels.medication.secondary_effects') %>:</b>
  	<% @facets.each do |term| %>
      <span class="label label-info"><%= term["term"] %> (<%= term["count"] %>) </span>&nbsp;
  	<% end %>
  	</ul>
  </p>
  <% @secondary_effects.each do |prescription| %>
    <div class="row well">
      <%= prescription.user.nickname.blank? ? t(:anonymous) : prescription.user.nickname %>
      <% prescription.secondary_effects_array.each do |tag| %>
        <span class="label label-info"><%= tag %></span>
      <% end %>
      <br/>
      <% if prescription.user_agent_info %>
        <span class="label label">
          <%= prescription.user_agent_info['platform']  %>
        </span>&nbsp;
      <% end %>
      <% if prescription.user_agent_info && prescription.user_agent_info['is_mobile'] %>
        <span class="label label-success">
          <%= t(:mobile) %>
        </span>
      <% end %>
    </div>
  <% end %>
  <br/>
  <%= paginate @secondary_effects %>
  <% if @experiences.count > 0 %>
    <h3>Experience</h3>
    <% @experiences.each do |prescription| %>
      <div class="row well">
        <%= prescription.experience %>
      </div>
    <% end %>
  <% end %>

  <%= render "actions", medication: @medication, with_show: false %>
</div>