config/routes.rb
BBPHealth::Application.routes.draw do

  scope "(:locale)", :locale => /en|fr/,  :defaults => {:locale => ""} do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get '/users/auth/:provider/setup'   => 'users/omniauth_callbacks#setup'
      get '/users/auth/facebook/callback' => 'users/omniauth_callbacks#facebook'
    end

    resources :medications do
      collection do
        get :search 
        get :list
        get :elastic_search
      end
      member do
        get :map
      end
      resources :secondary_effects
    end
    
    root :to => "medications#index"
    match "secondary_effects" =>"secondary_effects#index" 
  end

  get '/map/:id/clusterize' => 'map#clusterize'
  get '/map/:id/select'     => 'map#select'
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end if flash%>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top <%= "admin_nav" if admin? %>">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "BBPHealth", root_path, :class => :brand %>
      <div class="nav-collapse">
        <% unless @home_page %>
          <%= form_tag elastic_search_medications_path, :method => 'get', :class => "navbar-search pull-left" do %>
            <%= text_field_tag :q, params[:q], :class => "search-query span4", :type => :search, :placeholder => t('medications.title') %>
          <% end %>
        <% end %>

        <ul class="nav pull-right">
          <% if user_signed_in?  && current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Listings", list_medications_path %></li>
              </ul>
            </li>
          <% end %>
          <% if user_signed_in?  %>
            <li class="">
               <%= link_to  current_user.email, edit_user_registration_path%>
            </li>
            <li class="">
              <%= link_to t('devise.shared.sign_out'), destroy_user_session_path, :method => :delete %>
            </li>
          <% else %>
            <li class="">
              <%= link_to t('devise.shared.sign_in'), new_user_session_path %>
            </li>
            <li class="">
              <%= link_to t('devise.shared.sign_up'), new_user_registration_path %>
            </li>
            <li class="">
              <%= link_to image_tag('fb_login_icon.gif'), "/users/auth/facebook" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BBPHealth</title>
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
  <%= stylesheet_link_tag  "application", "vendor" %>
  <!--[if lte IE 8]><link rel="stylesheet" href="/leaflet.ie.css" /><![endif]-->

  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <%= render '/layouts/header' %>
  <div class="container" id="container">
   <%= render '/layouts/flash_messages' %>
   <%= yield %>
  </div>
  <%= javascript_include_tag "application", "vendor" %>
  <%= javascript_include_tag BBPHealth::Application.config.clusterer_url + "/assets/v1/leaflet_clusterer.js" %>
  <%= yield :tail %>
</body>
</html>